spring:
  profiles:
    active: te
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html


  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  messages:
    basename: il8n/messages
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #        filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

server:
  servlet:
    context-path: /dd
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: 'null'

shiro:
  expireIn: 1800
  sessionTimeout: 1800000
  cookieTimeout: 2592000

  sessionIdName: session.id



---
spring:
  profiles: de
  datasource:
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://10.1.*****:****/healthcloud_questionnaire?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
    username: xxxxx
    password: xxxxx


---
spring:
  profiles: te
  datasource:
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://10.1.*****:****/healthcloud_questionnaire?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull
    username: xxxxx
    password: xxxxx
